import { litToReact } from "./tools";
import { MdElevatedButton as M_ElevatedButton } from '@material/web/button/elevated-button';
import { type MdElevatedButtonProps } from './converted-components.d';
export const MdElevatedButton = litToReact<MdElevatedButtonProps>(M_ElevatedButton);
import { MdFilledButton as M_FilledButton } from '@material/web/button/filled-button';
import { type MdFilledButtonProps } from './converted-components.d';
export const MdFilledButton = litToReact<MdFilledButtonProps>(M_FilledButton);
import { MdFilledTonalButton as M_FilledTonalButton } from '@material/web/button/filled-tonal-button';
import { type MdFilledTonalButtonProps } from './converted-components.d';
export const MdFilledTonalButton = litToReact<MdFilledTonalButtonProps>(M_FilledTonalButton);
import { MdOutlinedButton as M_OutlinedButton } from '@material/web/button/outlined-button';
import { type MdOutlinedButtonProps } from './converted-components.d';
export const MdOutlinedButton = litToReact<MdOutlinedButtonProps>(M_OutlinedButton);
import { MdTextButton as M_TextButton } from '@material/web/button/text-button';
import { type MdTextButtonProps } from './converted-components.d';
export const MdTextButton = litToReact<MdTextButtonProps>(M_TextButton);
import { MdCheckbox as M_Checkbox } from '@material/web/checkbox/checkbox';
import { type MdCheckboxProps } from './converted-components.d';
export const MdCheckbox = litToReact<MdCheckboxProps>(M_Checkbox);
import { MdAssistChip as M_AssistChip } from '@material/web/chips/assist-chip';
import { type MdAssistChipProps } from './converted-components.d';
export const MdAssistChip = litToReact<MdAssistChipProps>(M_AssistChip);
import { MdChipSet as M_ChipSet } from '@material/web/chips/chip-set';
import { type MdChipSetProps } from './converted-components.d';
export const MdChipSet = litToReact<MdChipSetProps>(M_ChipSet);
import { MdFilterChip as M_FilterChip } from '@material/web/chips/filter-chip';
import { type MdFilterChipProps } from './converted-components.d';
export const MdFilterChip = litToReact<MdFilterChipProps>(M_FilterChip);
import { MdInputChip as M_InputChip } from '@material/web/chips/input-chip';
import { type MdInputChipProps } from './converted-components.d';
export const MdInputChip = litToReact<MdInputChipProps>(M_InputChip);
import { MdSuggestionChip as M_SuggestionChip } from '@material/web/chips/suggestion-chip';
import { type MdSuggestionChipProps } from './converted-components.d';
export const MdSuggestionChip = litToReact<MdSuggestionChipProps>(M_SuggestionChip);
import { MdDialog as M_Dialog } from '@material/web/dialog/dialog';
import { type MdDialogProps } from './converted-components.d';
export const MdDialog = litToReact<MdDialogProps>(M_Dialog);
import { MdDivider as M_Divider } from '@material/web/divider/divider';
import { type MdDividerProps } from './converted-components.d';
export const MdDivider = litToReact<MdDividerProps>(M_Divider);
import { MdElevation as M_Elevation } from '@material/web/elevation/elevation';
import { type MdElevationProps } from './converted-components.d';
export const MdElevation = litToReact<MdElevationProps>(M_Elevation);
import { MdBrandedFab as M_BrandedFab } from '@material/web/fab/branded-fab';
import { type MdBrandedFabProps } from './converted-components.d';
export const MdBrandedFab = litToReact<MdBrandedFabProps>(M_BrandedFab);
import { MdFab as M_Fab } from '@material/web/fab/fab';
import { type MdFabProps } from './converted-components.d';
export const MdFab = litToReact<MdFabProps>(M_Fab);
import { MdFilledField as M_FilledField } from '@material/web/field/filled-field';
import { type MdFilledFieldProps } from './converted-components.d';
export const MdFilledField = litToReact<MdFilledFieldProps>(M_FilledField);
import { MdOutlinedField as M_OutlinedField } from '@material/web/field/outlined-field';
import { type MdOutlinedFieldProps } from './converted-components.d';
export const MdOutlinedField = litToReact<MdOutlinedFieldProps>(M_OutlinedField);
import { MdFocusRing as M_MdFocusRing } from '@material/web/focus/md-focus-ring';
import { type MdFocusRingProps } from './converted-components.d';
export const MdFocusRing = litToReact<MdFocusRingProps>(M_MdFocusRing);
import { MdIcon as M_Icon } from '@material/web/icon/icon';
import { type MdIconProps } from './converted-components.d';
export const MdIcon = litToReact<MdIconProps>(M_Icon);
import { MdFilledIconButton as M_FilledIconButton } from '@material/web/iconbutton/filled-icon-button';
import { type MdFilledIconButtonProps } from './converted-components.d';
export const MdFilledIconButton = litToReact<MdFilledIconButtonProps>(M_FilledIconButton);
import { MdFilledTonalIconButton as M_FilledTonalIconButton } from '@material/web/iconbutton/filled-tonal-icon-button';
import { type MdFilledTonalIconButtonProps } from './converted-components.d';
export const MdFilledTonalIconButton = litToReact<MdFilledTonalIconButtonProps>(M_FilledTonalIconButton);
import { MdIconButton as M_IconButton } from '@material/web/iconbutton/icon-button';
import { type MdIconButtonProps } from './converted-components.d';
export const MdIconButton = litToReact<MdIconButtonProps>(M_IconButton);
import { MdOutlinedIconButton as M_OutlinedIconButton } from '@material/web/iconbutton/outlined-icon-button';
import { type MdOutlinedIconButtonProps } from './converted-components.d';
export const MdOutlinedIconButton = litToReact<MdOutlinedIconButtonProps>(M_OutlinedIconButton);
import { MdListItem as M_ListItem } from '@material/web/list/list-item';
import { type MdListItemProps } from './converted-components.d';
export const MdListItem = litToReact<MdListItemProps>(M_ListItem);
import { MdList as M_List } from '@material/web/list/list';
import { type MdListProps } from './converted-components.d';
export const MdList = litToReact<MdListProps>(M_List);
import { MdMenuItem as M_MenuItem } from '@material/web/menu/menu-item';
import { type MdMenuItemProps } from './converted-components.d';
export const MdMenuItem = litToReact<MdMenuItemProps>(M_MenuItem);
import { MdMenu as M_Menu } from '@material/web/menu/menu';
import { type MdMenuProps } from './converted-components.d';
export const MdMenu = litToReact<MdMenuProps>(M_Menu);
import { MdSubMenu as M_SubMenu } from '@material/web/menu/sub-menu';
import { type MdSubMenuProps } from './converted-components.d';
export const MdSubMenu = litToReact<MdSubMenuProps>(M_SubMenu);
import { MdCircularProgress as M_CircularProgress } from '@material/web/progress/circular-progress';
import { type MdCircularProgressProps } from './converted-components.d';
export const MdCircularProgress = litToReact<MdCircularProgressProps>(M_CircularProgress);
import { MdLinearProgress as M_LinearProgress } from '@material/web/progress/linear-progress';
import { type MdLinearProgressProps } from './converted-components.d';
export const MdLinearProgress = litToReact<MdLinearProgressProps>(M_LinearProgress);
import { MdRadio as M_Radio } from '@material/web/radio/radio';
import { type MdRadioProps } from './converted-components.d';
export const MdRadio = litToReact<MdRadioProps>(M_Radio);
import { MdRipple as M_Ripple } from '@material/web/ripple/ripple';
import { type MdRippleProps } from './converted-components.d';
export const MdRipple = litToReact<MdRippleProps>(M_Ripple);
import { MdFilledSelect as M_FilledSelect } from '@material/web/select/filled-select';
import { type MdFilledSelectProps } from './converted-components.d';
export const MdFilledSelect = litToReact<MdFilledSelectProps>(M_FilledSelect);
import { MdOutlinedSelect as M_OutlinedSelect } from '@material/web/select/outlined-select';
import { type MdOutlinedSelectProps } from './converted-components.d';
export const MdOutlinedSelect = litToReact<MdOutlinedSelectProps>(M_OutlinedSelect);
import { MdSelectOption as M_SelectOption } from '@material/web/select/select-option';
import { type MdSelectOptionProps } from './converted-components.d';
export const MdSelectOption = litToReact<MdSelectOptionProps>(M_SelectOption);
import { MdSlider as M_Slider } from '@material/web/slider/slider';
import { type MdSliderProps } from './converted-components.d';
export const MdSlider = litToReact<MdSliderProps>(M_Slider);
import { MdSwitch as M_Switch } from '@material/web/switch/switch';
import { type MdSwitchProps } from './converted-components.d';
export const MdSwitch = litToReact<MdSwitchProps>(M_Switch);
import { MdPrimaryTab as M_PrimaryTab } from '@material/web/tabs/primary-tab';
import { type MdPrimaryTabProps } from './converted-components.d';
export const MdPrimaryTab = litToReact<MdPrimaryTabProps>(M_PrimaryTab);
import { MdSecondaryTab as M_SecondaryTab } from '@material/web/tabs/secondary-tab';
import { type MdSecondaryTabProps } from './converted-components.d';
export const MdSecondaryTab = litToReact<MdSecondaryTabProps>(M_SecondaryTab);
import { MdTabs as M_Tabs } from '@material/web/tabs/tabs';
import { type MdTabsProps } from './converted-components.d';
export const MdTabs = litToReact<MdTabsProps>(M_Tabs);
import { MdFilledTextField as M_FilledTextField } from '@material/web/textfield/filled-text-field';
import { type MdFilledTextFieldProps } from './converted-components.d';
export const MdFilledTextField = litToReact<MdFilledTextFieldProps>(M_FilledTextField);
import { MdOutlinedTextField as M_OutlinedTextField } from '@material/web/textfield/outlined-text-field';
import { type MdOutlinedTextFieldProps } from './converted-components.d';
export const MdOutlinedTextField = litToReact<MdOutlinedTextFieldProps>(M_OutlinedTextField);