import { type MdBadgeProps } from "./converted-components.d";
export declare const MdBadge: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdBadgeProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdElevatedCardProps } from "./converted-components.d";
export declare const MdElevatedCard: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdElevatedCardProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdFilledCardProps } from "./converted-components.d";
export declare const MdFilledCard: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdFilledCardProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdOutlinedCardProps } from "./converted-components.d";
export declare const MdOutlinedCard: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdOutlinedCardProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdItemProps } from "./converted-components.d";
export declare const MdItem: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdItemProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdNavigationBarProps } from "./converted-components.d";
export declare const MdNavigationBar: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdNavigationBarProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdNavigationDrawerModalProps } from "./converted-components.d";
export declare const MdNavigationDrawerModal: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdNavigationDrawerModalProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdNavigationDrawerProps } from "./converted-components.d";
export declare const MdNavigationDrawer: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdNavigationDrawerProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdNavigationTabProps } from "./converted-components.d";
export declare const MdNavigationTab: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdNavigationTabProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdOutlinedSegmentedButtonProps } from "./converted-components.d";
export declare const MdOutlinedSegmentedButton: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdOutlinedSegmentedButtonProps>, string | import("react").JSXElementConstructor<any>>;
import { type MdOutlinedSegmentedButtonSetProps } from "./converted-components.d";
export declare const MdOutlinedSegmentedButtonSet: ({ ...props }: import("react").ClassAttributes<HTMLDivElement> & import("react").HTMLAttributes<HTMLDivElement>) => import("react").ReactElement<import("react").JSXElementConstructor<MdOutlinedSegmentedButtonSetProps>, string | import("react").JSXElementConstructor<any>>;
